{"uuid": "85fa494e-2995-4809-a0db-a8a789f5011f", "children": ["477eefa0-d18c-4826-8e32-ccc4e5ac9596"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//input[@id='gnb_search']\"}\n  (Session info: chrome=134.0.6998.165); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n#0 0x558fb3fc5ffa <unknown>\n#1 0x558fb3a84970 <unknown>\n#2 0x558fb3ad6385 <unknown>\n#3 0x558fb3ad65b1 <unknown>\n#4 0x558fb3b253c4 <unknown>\n#5 0x558fb3afc2bd <unknown>\n#6 0x558fb3b2270c <unknown>\n#7 0x558fb3afc063 <unknown>\n#8 0x558fb3ac8328 <unknown>\n#9 0x558fb3ac9491 <unknown>\n#10 0x558fb3f8d42b <unknown>\n#11 0x558fb3f912ec <unknown>\n#12 0x558fb3f74a22 <unknown>\n#13 0x558fb3f91e64 <unknown>\n#14 0x558fb3f58bef <unknown>\n#15 0x558fb3fb4558 <unknown>\n#16 0x558fb3fb4736 <unknown>\n#17 0x558fb3fc4e76 <unknown>\n#18 0x7f0dc409caa4 <unknown>\n#19 0x7f0dc4129c3c <unknown>\n\n", "trace": "  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/src/tests/ui_tests/conftest.py\", line 28, in driver\n    driver.find_element(By.XPATH,\"//input[@id='gnb_search']\").click()\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 770, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 384, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1742954045275, "stop": 1742954058980}], "start": 1742954045275, "stop": 1742954059055}