{"uuid": "54c56d5e-b0ac-4599-8ce9-751b216100b4", "children": ["ac6c2bea-ddfe-4e24-b73a-f75ac914833b", "9a161adf-c026-45c8-b05d-7ae2ff8fd802", "4b934cc9-d67a-422d-9373-d4aa447215e2", "efb3dfc5-0f66-4308-a717-ed4ab4ffe457", "8421420b-b2bf-4a4c-a6c5-b14dc246b779", "6cec9052-7b82-42db-98a5-9376ddbc0b0b", "94c73b8c-0b23-4f38-8274-cab149ed72da", "b6244c71-7a04-4f97-9fbb-898d55913e34", "bc9ee174-20da-4137-af43-fd87f733ab67", "31c19a20-390b-42d7-b41d-586625088520"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x556cda308ffa <unknown>\n#1 0x556cd9dc7970 <unknown>\n#2 0x556cd9e19385 <unknown>\n#3 0x556cd9e195b1 <unknown>\n#4 0x556cd9e683c4 <unknown>\n#5 0x556cd9e3f2bd <unknown>\n#6 0x556cd9e6570c <unknown>\n#7 0x556cd9e3f063 <unknown>\n#8 0x556cd9e0b328 <unknown>\n#9 0x556cd9e0c491 <unknown>\n#10 0x556cda2d042b <unknown>\n#11 0x556cda2d42ec <unknown>\n#12 0x556cda2b7a22 <unknown>\n#13 0x556cda2d4e64 <unknown>\n#14 0x556cda29bbef <unknown>\n#15 0x556cda2f7558 <unknown>\n#16 0x556cda2f7736 <unknown>\n#17 0x556cda307e76 <unknown>\n#18 0x7f06ab69caa4 <unknown>\n#19 0x7f06ab729c3c <unknown>\n\n", "trace": "  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/src/tests/ui_tests/conftest.py\", line 30, in driver\n    WebDriverWait(driver, 10).until(\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/support/wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1743024837642, "stop": 1743024851239}], "start": 1743024837642, "stop": 1743024851295}