{"uuid": "1d2942f2-78f6-4b03-a34e-541b57129088", "children": ["2f70f793-9cab-4981-bfb2-9ab62ccca915", "30572e01-cdcc-4f03-8006-e25473bcd2f6", "fbc67680-acfb-4270-9af1-1fd1449a9649", "fb157cfc-5a2a-4462-a6c9-9b9646027b3d", "fedde092-f48a-4f48-af27-0ccf744c44d8", "61444944-c3f4-463e-8f8d-3a8c1a230cb8", "a8d2111e-ee77-48f0-8dd0-0dde5ce84853", "b6056241-9ac2-4361-a695-e3a187647016", "ed034d4e-1205-4b5c-8923-16dff56fdb84", "12217d31-feea-44d7-a542-3a98f78ffbd3"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x557722edaffa <unknown>\n#1 0x557722999970 <unknown>\n#2 0x5577229eb385 <unknown>\n#3 0x5577229eb5b1 <unknown>\n#4 0x557722a3a3c4 <unknown>\n#5 0x557722a112bd <unknown>\n#6 0x557722a3770c <unknown>\n#7 0x557722a11063 <unknown>\n#8 0x5577229dd328 <unknown>\n#9 0x5577229de491 <unknown>\n#10 0x557722ea242b <unknown>\n#11 0x557722ea62ec <unknown>\n#12 0x557722e89a22 <unknown>\n#13 0x557722ea6e64 <unknown>\n#14 0x557722e6dbef <unknown>\n#15 0x557722ec9558 <unknown>\n#16 0x557722ec9736 <unknown>\n#17 0x557722ed9e76 <unknown>\n#18 0x7f60d349caa4 <unknown>\n#19 0x7f60d3529c3c <unknown>\n\n", "trace": "  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/src/tests/ui_tests/conftest.py\", line 30, in driver\n    WebDriverWait(driver, 10).until(\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/support/wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1743000395319, "stop": 1743000407373}], "start": 1743000395319, "stop": 1743000407428}