{"uid":"a2093c896283b7e4","name":"FAILED 기능 동작 하는지 확인","fullName":"src.tests.ui_tests.test_fail_screenshot#test_fail_screenshot","historyId":"295b0300b44e64aac7e9de8f2dd396ad","time":{"start":1746451442512,"stop":1746451444905,"duration":2393},"description":"\n일부러 실패하게 만드는 테스트\n- 올바르지 않은 요소 선택\n- 검색창이 없는 요소를 클릭 시도하여 실패 유발\n","descriptionHtml":"<p>일부러 실패하게 만드는 테스트</p>\n<ul>\n<li>올바르지 않은 요소 선택</li>\n<li>검색창이 없는 요소를 클릭 시도하여 실패 유발</li>\n</ul>\n","status":"failed","statusMessage":"Failed: \uD83D\uDCCC 예상된 실패: 잘못된 XPATH로 인해 클릭할 수 없음","statusTrace":"src/tests/ui_tests/test_fail_screenshot.py:17: in test_fail_screenshot\n    driver.find_element(By.XPATH, \"//input[@id='wrong_search_id']\").click()\n/usr/local/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:917: in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n/usr/local/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:448: in execute\n    self.error_handler.check_response(response)\n/usr/local/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py:232: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//input[@id='wrong_search_id']\"}\nE     (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nE   Stacktrace:\nE   #0 0x5594982b47fa <unknown>\nE   #1 0x559497d58e90 <unknown>\nE   #2 0x559497daa870 <unknown>\nE   #3 0x559497daaa61 <unknown>\nE   #4 0x559497df8cb4 <unknown>\nE   #5 0x559497dd026d <unknown>\nE   #6 0x559497df6135 <unknown>\nE   #7 0x559497dd0013 <unknown>\nE   #8 0x559497d9cb3b <unknown>\nE   #9 0x559497d9d7a1 <unknown>\nE   #10 0x559498279b9b <unknown>\nE   #11 0x55949827da8a <unknown>\nE   #12 0x559498261912 <unknown>\nE   #13 0x55949827e604 <unknown>\nE   #14 0x55949824674f <unknown>\nE   #15 0x5594982a2678 <unknown>\nE   #16 0x5594982a2856 <unknown>\nE   #17 0x5594982b3666 <unknown>\nE   #18 0x7f1ab22351f5 <unknown>\n\nDuring handling of the above exception, another exception occurred:\nsrc/tests/ui_tests/test_fail_screenshot.py:20: in test_fail_screenshot\n    pytest.fail(\"\uD83D\uDCCC 예상된 실패: 잘못된 XPATH로 인해 클릭할 수 없음\")\nE   Failed: \uD83D\uDCCC 예상된 실패: 잘못된 XPATH로 인해 클릭할 수 없음","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"description":"\n일부러 실패하게 만드는 테스트\n- 올바르지 않은 요소 선택\n- 검색창이 없는 요소를 클릭 시도하여 실패 유발\n","status":"failed","statusMessage":"Failed: \uD83D\uDCCC 예상된 실패: 잘못된 XPATH로 인해 클릭할 수 없음","statusTrace":"src/tests/ui_tests/test_fail_screenshot.py:17: in test_fail_screenshot\n    driver.find_element(By.XPATH, \"//input[@id='wrong_search_id']\").click()\n/usr/local/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:917: in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n/usr/local/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:448: in execute\n    self.error_handler.check_response(response)\n/usr/local/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py:232: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//input[@id='wrong_search_id']\"}\nE     (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nE   Stacktrace:\nE   #0 0x5594982b47fa <unknown>\nE   #1 0x559497d58e90 <unknown>\nE   #2 0x559497daa870 <unknown>\nE   #3 0x559497daaa61 <unknown>\nE   #4 0x559497df8cb4 <unknown>\nE   #5 0x559497dd026d <unknown>\nE   #6 0x559497df6135 <unknown>\nE   #7 0x559497dd0013 <unknown>\nE   #8 0x559497d9cb3b <unknown>\nE   #9 0x559497d9d7a1 <unknown>\nE   #10 0x559498279b9b <unknown>\nE   #11 0x55949827da8a <unknown>\nE   #12 0x559498261912 <unknown>\nE   #13 0x55949827e604 <unknown>\nE   #14 0x55949824674f <unknown>\nE   #15 0x5594982a2678 <unknown>\nE   #16 0x5594982a2856 <unknown>\nE   #17 0x5594982b3666 <unknown>\nE   #18 0x7f1ab22351f5 <unknown>\n\nDuring handling of the above exception, another exception occurred:\nsrc/tests/ui_tests/test_fail_screenshot.py:20: in test_fail_screenshot\n    pytest.fail(\"\uD83D\uDCCC 예상된 실패: 잘못된 XPATH로 인해 클릭할 수 없음\")\nE   Failed: \uD83D\uDCCC 예상된 실패: 잘못된 XPATH로 인해 클릭할 수 없음","steps":[],"attachments":[{"uid":"2a992099be4ccbf2","name":"Failure Screenshot","source":"2a992099be4ccbf2.png","type":"image/png","size":51535}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"story","value":"검색창 FAILED 테스트"},{"name":"feature","value":"UI 테스트"},{"name":"parentSuite","value":"src.tests.ui_tests"},{"name":"suite","value":"test_fail_screenshot"},{"name":"host","value":"bcd5245c32dc"},{"name":"thread","value":"15-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"src.tests.ui_tests.test_fail_screenshot"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"a2093c896283b7e4.json","parameterValues":[]}