{"uid":"b1cff74fbdb4fc01","name":"FAILED 기능 동작 하는지 확인","fullName":"src.tests.ui_tests.test_fail_screenshot#test_fail_screenshot","historyId":"295b0300b44e64aac7e9de8f2dd396ad","time":{"start":1746448313909,"stop":1746448313909,"duration":0},"description":"\n일부러 실패하게 만드는 테스트\n- 올바르지 않은 요소 선택\n- 검색창이 없는 요소를 클릭 시도하여 실패 유발\n","descriptionHtml":"<p>일부러 실패하게 만드는 테스트</p>\n<ul>\n<li>올바르지 않은 요소 선택</li>\n<li>검색창이 없는 요소를 클릭 시도하여 실패 유발</li>\n</ul>\n","status":"broken","statusMessage":"IndexError: tuple index out of range","statusTrace":"/usr/local/lib/python3.13/site-packages/webdriver_manager/core/file_manager.py:65: in __extract_zip\n    archive.extractall(to_directory)\n/usr/local/lib/python3.13/zipfile/__init__.py:1788: in extractall\n    self._extract_member(zipinfo, path, pwd)\n/usr/local/lib/python3.13/zipfile/__init__.py:1850: in _extract_member\n    shutil.copyfileobj(source, target)\n/usr/local/lib/python3.13/shutil.py:203: in copyfileobj\n    while buf := fsrc_read(length):\n/usr/local/lib/python3.13/zipfile/__init__.py:1015: in read\n    data = self._read1(n)\n/usr/local/lib/python3.13/zipfile/__init__.py:1083: in _read1\n    data += self._read2(n - len(data))\n/usr/local/lib/python3.13/zipfile/__init__.py:1118: in _read2\n    raise EOFError\nE   EOFError\n\nDuring handling of the above exception, another exception occurred:\nsrc/tests/conftest.py:31: in driver\n    service = Service(ChromeDriverManager().install())\n/usr/local/lib/python3.13/site-packages/webdriver_manager/chrome.py:40: in install\n    driver_path = self._get_driver_binary_path(self.driver)\n/usr/local/lib/python3.13/site-packages/webdriver_manager/core/manager.py:41: in _get_driver_binary_path\n    binary_path = self._cache_manager.save_file_to_cache(driver, file)\n/usr/local/lib/python3.13/site-packages/webdriver_manager/core/driver_cache.py:54: in save_file_to_cache\n    files = self.unpack_archive(archive, path)\n/usr/local/lib/python3.13/site-packages/webdriver_manager/core/driver_cache.py:49: in unpack_archive\n    return self._file_manager.unpack_archive(archive, path)\n/usr/local/lib/python3.13/site-packages/webdriver_manager/core/file_manager.py:57: in unpack_archive\n    return self.__extract_zip(archive_file, target_dir)\n/usr/local/lib/python3.13/site-packages/webdriver_manager/core/file_manager.py:67: in __extract_zip\n    if e.args[0] not in [26, 13] and e.args[1] not in [\nE   IndexError: tuple index out of range","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"story","value":"검색창 FAILED 테스트"},{"name":"feature","value":"UI 테스트"},{"name":"parentSuite","value":"src.tests.ui_tests"},{"name":"suite","value":"test_fail_screenshot"},{"name":"host","value":"a8ddaefeb69f"},{"name":"thread","value":"15-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"src.tests.ui_tests.test_fail_screenshot"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"b1cff74fbdb4fc01.json","parameterValues":[]}